CREATE TABLE player (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE wallet (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    balance   BIGINT NOT NULL DEFAULT 0,
    version   INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_wallet_player UNIQUE (player_id),
    CONSTRAINT fk_wallet_player FOREIGN KEY (player_id) REFERENCES player (id)
);

CREATE TABLE ledger_entry (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id                BIGINT      NOT NULL,
    amount                   BIGINT      NOT NULL,
    direction                VARCHAR(16) NOT NULL,
    reason_kind              VARCHAR(32) NOT NULL,
    description              VARCHAR(255) NOT NULL,
    request_id               VARCHAR(36) NOT NULL,
    original_ledger_entry_id BIGINT,
    created_at               TIMESTAMP   NOT NULL,
    CONSTRAINT uq_ledger_request_id UNIQUE (request_id),
    CONSTRAINT uq_ledger_original_ledger_entry_id UNIQUE (original_ledger_entry_id),
    CONSTRAINT fk_ledger_wallet FOREIGN KEY (wallet_id) REFERENCES wallet (id)
);
